jobboard/urls.py
from django.urls import path
from . import views

app_name = 'jobboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_post', views.create_post, name = "create_post"),
    path('create_stage', views.create_stage, name = "create_stage"),
    path('get_updates', views.get_updates, name = "get_updates"),
    path('<int:stage_id>/edit_stage', views.edit_stage, name = "edit_stage"),
    path('<int:stage_id>/delete_stage', views.delete_stage, name = "delete_stage"),
    path('<int:posting_id>/delete_post', views.delete_post, name = "delete_post"),
    path('<int:posting_id>/detail_view', views.detail_view, name = "detail_view"),
    path('<int:posting_id>/edit_post', views.edit_post, name = "edit_post")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from jobboard import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('jobboard/', include('jobboard.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

jobboard/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Stage(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    stage_title = models.CharField(max_length=200)
    def __str__(self):
        return self.stage_title

    def ordered_posting_set(self):
        return self.posting_set.all().order_by('deadline')
        
class Posting(models.Model):
    stage = models.ForeignKey(Stage, on_delete=models.CASCADE, blank=True, null=True)
    company =  models.CharField(max_length=200, blank=True, null=True)
    job_title = models.CharField(max_length=200, blank=True, null=True)
    deadline = models.DateTimeField('Next Deadline', blank=True, null=True)
    job_description = models.TextField('Descripton', blank=True, null=True)
    job_url = models.URLField(max_length=200, blank=True, default = '')
    job_email = models.CharField('email', max_length=200, blank=True, default = '')
    def __str__(self):
        return self.job_title
    def date_passed(self):
        return self.deadline >= timezone.now()

class UpdateTime(models.Model):
    CHOICES = (
        ('day','Daily'),
        ('hour', 'Hourly'),
        ('none', 'Never')
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    update_time = models.CharField('Recieve Updates on ', max_length=200, choices = CHOICES)
    def __str__(self):
        return self.update_time

jobboard/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Posting, Stage, UpdateTime
from django import forms

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
class EditStageForm(forms.ModelForm):
    class Meta:
        model = Stage
        fields = ['author', 'stage_title']

    def __init__(self, * args, ** kwargs):
        self.request = kwargs.pop("request")
        super(EditStageForm, self).__init__( * args, ** kwargs)
        self.fields["author"].initial = self.request.user
        self.fields["author"].widget = forms.HiddenInput()
    
class EditPostForm(forms.ModelForm):
    class Meta:
        model = Posting
        fields = ['stage', 'company', 'job_title', 'deadline', 'job_description', 'job_url', 'job_email']

    def __init__(self, * args, ** kwargs):
        self.request = kwargs.pop("request")
        super(EditPostForm, self).__init__( * args, ** kwargs)
        self.fields["stage"].queryset = Stage.objects.filter(author = self.request.user)
        self.fields["job_description"].strip = False
    
    def clean(self):
        super(EditPostForm, self).clean()
         
        stage = self.cleaned_data.get('stage')
        job_title = self.cleaned_data.get('job_title')
 
        if stage is None:
            self._errors['stage'] = self.error_class([
                'Required Field'])
        if job_title is None:
            self._errors['stage'] = self.error_class([
                'Required Field'])
 
        return self.cleaned_data

class UpdateTimeForm(forms.ModelForm):
    class Meta:
        model = UpdateTime
        fields = '__all__'

    def __init__(self, * args, ** kwargs):
        self.request = kwargs.pop("request")
        super(UpdateTimeForm, self).__init__( * args, ** kwargs)
        self.fields["author"].initial = self.request.user
        self.fields["author"].widget = forms.HiddenInput()

jobboard/views.py
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.http import HttpResponseServerError, JsonResponse
from .models import Stage, Posting
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import EditPostForm, UserRegisterForm, EditStageForm, UpdateTimeForm
import logging


@login_required
def index(request):
    if request.method == "POST":
        try:
          logger = logging.getLogger("mylogger")
          body_unicode = request.body.decode('utf-8')
          body_unicode = body_unicode.replace('id=', '')
          body_unicode = body_unicode.replace('"', '')
          body_unicode = body_unicode.replace('[', '')
          body_unicode = body_unicode.replace(']', '')
          arr = body_unicode.split(',')
          idx = 0
          for curr_stage in Stage.objects.filter(author = request.user):
            q1 = arr[idx]
            arr1 = q1.split('&')
            idx += 1
            if len(arr1) == 1 and arr1[0] == '':
               continue
            for curr in arr1:
              posting = Posting.objects.get(id=curr)
              if posting not in Posting.objects.filter(stage = curr_stage):
                posting.stage = curr_stage
                posting.save()

        except KeyError:
            HttpResponseServerError("Malformed data!")

        return JsonResponse({"success": True}, status=200)
    else:
      latest_stage_list = Stage.objects.filter(author = request.user)
      context = {
          'latest_stage_list': latest_stage_list,
      }
      return render(request, 'jobboard/index.html', context)

@login_required
def detail_view(request, posting_id):
    posting = get_object_or_404(Posting, pk=posting_id)
    return render(request, 'jobboard/detail_view.html', {'posting': posting})

@login_required
def edit_post(request, posting_id):
  context = {}
  posting = get_object_or_404(Posting, pk=posting_id)
  form = EditPostForm(request.POST or None, request = request, instance = posting)
  form.fields["job_title"].text = posting.job_title
  if form.is_valid():
    form.save()
    return HttpResponseRedirect("detail_view")
  context["form"] = form
  return render(request, 'jobboard/edit_post.html', context)

@login_required
def create_post(request):
  context = {}
  form = EditPostForm(request.POST or None, request = request)
  if form.is_valid():
    form.save()
    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)
  context["form"] = form
  return render(request, 'jobboard/create_post.html', context)

@login_required
def get_updates(request):
  context = {}
  form = UpdateTimeForm(request.POST or None, request = request)
  if form.is_valid():
    form.save()
    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)
  context["form"] = form
  return render(request, 'jobboard/get_updates.html', context)

@login_required
def create_stage(request):
  context = {}
  form = EditStageForm(request.POST or None, request = request)
  if form.is_valid():
    form.save()
    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)
  context["form"] = form
  return render(request, 'jobboard/create_stage.html', context)

@login_required
def edit_stage(request, stage_id):
  context = {}
  stage = get_object_or_404(Stage, pk=stage_id)
  form = EditStageForm(request.POST or None, request = request, instance = stage)
  if form.is_valid():
    form.save()
    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)
  context["form"] = form
  return render(request, 'jobboard/edit_stage.html', context)

@login_required
def delete_post(request, posting_id):
    context ={}
    posting = get_object_or_404(Posting, pk=posting_id)
 
    if request.method =="POST":
        posting.delete()
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)
    return render(request, "jobboard/delete_post.html", context)

@login_required
def delete_stage(request, stage_id):
    context ={}
    stage = get_object_or_404(Stage, pk=stage_id)
 
    if request.method =="POST":
        stage.delete()
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)
    return render(request, "jobboard/delete_stage.html", context)

def register(request):
    if request.method == 'POST':
      form = UserRegisterForm(request.POST)
      if form.is_valid(): 
        form.save()
        return HttpResponseRedirect(request.POST.get('next','/jobboard/'))
    else:
      form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})

jobboard/templates/jobboard/create_post.html
{% load crispy_forms_tags %}
{% load static %}
<title>Create Post</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href='{% static "styles.css" %}'>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="main">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{% url 'jobboard:index' %}">
        <input type="submit" value="Submit">
    </form>
 
</div>

jobboard/templates/jobboard/create_stage.html
{% load crispy_forms_tags %}
{% load static %}
<title>Create Stage</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href='{% static "styles.css" %}'>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="main">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{% url 'jobboard:index' %}">
        <input type="submit" value="Submit">
    </form>
 
</div>

jobboard/templates/jobboard/delete_post.html
{% load crispy_forms_tags %}
{% load static %}
<title>Delete Post</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="main">
    <form method="POST">
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="hidden" name="next" value="{% url 'jobboard:index' %}">
        <a href="/jobboard">Cancel </a>  
        <input type="submit" value="Yes" />
    </form>
</div>

jobboard/templates/jobboard/delete_stage.html
{% load crispy_forms_tags %}
{% load static %}
<title>Delete Stage</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="main">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href='{% static "styles.css" %}'>
    <form method="POST">
        {% csrf_token %}
        Are you want to delete this item ? This action will delete all associated posts.
        <input type="hidden" name="next" value="{% url 'jobboard:index' %}">
        <input type="submit" value="Yes" />
        <a href="/jobboard">Cancel </a>
    </form>
</div>

jobboard/templates/jobboard/detail_view.html
{% load static %}
{% load crispy_forms_tags %}
<title>Detail view</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href='{% static "styles.css" %}'>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
div {
    white-space: pre-wrap;
}
body{
margin-left:15%;
}
</style>
<div class="sidenav">
    {% if user.is_authenticated %}
    <div> <h2> Hi {{ user.username }}! </h2> </div>
    <a href="{% url 'jobboard:edit_post' posting.id %}" class="button">Edit</a>
    <a href="{% url 'jobboard:index' %}" class="button">Back</a>
    <a href="{% url 'jobboard:delete_post' posting.id %}" class="button">Delete</a> 
<a href="{% url 'logout' %}"> Log Out <span class = "glyphicon glyphicon-log-out"></span></a>
</div>
{% endif %}

<body>
    <h1>{{ posting.job_title }}</h1>
    <div>{{ posting.company }}</div>
    <div>{{ posting.deadline|date:"Y-m-d"}}</div>
    <div>{{ posting.job_description}}</div>
    <a href = '{{posting.job_url}}' class = "widget-49-meeting-points">{{posting.job_url}}</a>
</body>

jobboard/templates/jobboard/edit_post.html
{% load crispy_forms_tags %}
{% load static %}
<title>Edit Post</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href='{% static "styles.css" %}'>

<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
 
        <!-- form as paragraph -->
        {{ form.as_p }}
 
        <input type="submit" value="Update">
    </form>
 
</div>

jobboard/templates/jobboard/edit_stage.html
{% load crispy_forms_tags %}
{% load static %}
<title>Edit Stage</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href='{% static "styles.css" %}'>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="main">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{% url 'jobboard:index' %}">
        <input type="submit" value="Submit">
    </form>
 
</div>

jobboard/templates/jobboard/get_updates.html
{% load crispy_forms_tags %}
{% load static %}
<title>Get Email Updates</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href='{% static "styles.css" %}'>
<div class="main">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{% url 'jobboard:index' %}">
        <input type="submit" value="Submit">
    </form>
 
</div>

jobboard/templates/jobboard/index.html
<!DOCTYPE html>
<html>
        <head>
            <div class="sidenav">
                {% if user.is_authenticated %}
                <div> <h2> Hi {{ user.username }}! </h2> </div>
                <a href="{% url 'jobboard:create_post'%}" > Create Post <span class = "glyphicon glyphicon-plus"></span></a>  
                <a href="{% url 'jobboard:get_updates'%}" class="button">Sign Up for Email Reminders</a> 
            <a href="{% url 'logout' %}"> Log Out <span class = "glyphicon glyphicon-log-out"></span></a>
            </div>

            <meta charset="utf-8">
            <title>My Job Applications</title>
            
            {% load static %}
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <link rel="stylesheet" type="text/css" href='{% static "styles.css" %}'>
            <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
            <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script> 
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
            .list-group-item{
            margin-top: 1%;
            margin-right: 1%;
            margin-bottom: 1%;
            margin-left: 1%;
            }
            body{
            margin-left:5%;
            padding: 0px 10px;
            }
            </style>
        </head>
        <body>
            <div class="container">
            <div class="row">
                    <ul class="list-group list-group-horizontal col-lg">
                        {% for stage in latest_stage_list %}
                            <li style="min-width:20%;" class="list-group-item ui-state-default">
                            <p> {{ stage.stage_title }} <a href="{% url 'jobboard:edit_stage' stage.id %}"><span class = "glyphicon glyphicon-edit"></span></a><a href="{% url 'jobboard:delete_stage' stage.id %}"><span class = "glyphicon glyphicon-remove"></span></a></p>     
                                <ul style = "min-height: 100px;" id = "{{ stage.stage_title }}" class="connectedSortable">
                                    {% for posting in stage.ordered_posting_set %}
                                        <li  id="entry_{{posting.id}}" class="ui-state-default card card-margin">
                                        <div class="card-body pt-0">
                                        <div class="widget-49">
                                        <div class="widget-49-title-wrapper">
                                            <div class = "widget-49-date-primary"><span class="widget-49-date-month">{{posting.deadline}}</span></div>    
                                        </div>
                                        <div class="widget-49-meeting-info">
                                            <span class="widget-49-pro-title"> {{posting.job_title}}</span>
                                        </div>
                                        <div class="widget-49-meeting-points">
                                            <p class = "widget-49-meeting-points"><span>{{posting.company}}</span></p>
                                        <a href = '{{posting.job_url}}' class = "widget-49-meeting-points">{{posting.job_url}}</a>
                                        <p class = "widget-49-meeting-points"><span>{{posting.job_email}}</span></p>
                                        </div>
                                        <div class="widget-49-meeting-action">
                                        <a class="btn btn-sm btn-flash-border-primary" href="{% url 'jobboard:detail_view' posting.id %}">More Info</a>
                                        </div>
                                        </div>
                                        </div>
                                        </li>
                                    {% endfor %}
                                </ul>  
                            </li>
                        {% endfor %}
                        <li >
                            <p style ="margin-left: 20%; margin-top: 100%;"><a  href="{% url 'jobboard:create_stage'%}" > Add Stage <span class = "glyphicon glyphicon-plus"></span></a></p> 
                        </li>  
                    </ul>

            </div>
            </div>
    
     </body>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a>
{% endif %}
</html>
<script src="{% static 'js/jquery-sortable.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script>
$(function() {
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
    });

var group = $(".connectedSortable" ).sortable({
        connectWith: '.connectedSortable',
        delay: 500,
        update: function () {
            const arr = [];
            {% for stage in latest_stage_list %}
                var data = $(document.getElementById("{{ stage.stage_title }}")).sortable("serialize", {key:"id"});
                arr.push(data)
            {% endfor %}
            $.ajax({
                        type: "POST",
                        data: JSON.stringify(arr),
                        url: ""
                    });
        },
});
}).disableSelection();
</script>
  